# Generated by Django 2.2.6 on 2019-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200, verbose_name='About Name')),
                ('about_text', models.TextField(verbose_name='About Text')),
            ],
        ),
    ]
